development:
  adapter: mysql2
  encoding: utf8
  host: '139.59.247.112'
  reconnect: false
  database: 'ordery'
  pool: 5
  username: 'playhouse'
  password: 'dellF912;'
  socket: /tmp/mysql.sock

test:
  database: ordery

production:
  adapter: mysql2
  pool: 5
  host: '139.59.247.112'
  database: "ordery"
  username: 'playhouse'
  password: 'dellF912;'


