default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: 'ordery'
  username: 'playhouse'
  password: 'dellF912;'
  host: '139.59.247.112'
  reconnect: true
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: 'ordery'
  username: 'playhouse'
  password: 'dellF912;'
  host: '139.59.247.112'
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: 'ordery'
  username: 'playhouse'
  password: 'dellF912;'
  host: '139.59.247.112'
  reconnect: true

