development:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  database: ordery
  pool: 5
  username: root
  password: 'dellF912;'
  socket: /tmp/mysql.sock

test:
  database: ordery

production:
  url: <%= ENV['DATABASE_URL'] %>
