default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'ordery' %>
  username: <%= ENV['DB_USER'] || 'deploy' %>
  password: <%= ENV['DB_PASS'] || 'dellF912;'%>
  host: <%= ENV['DB_HOST'] || '188.166.185.184'%>
  url: <%= ENV['DB_URL'] %>
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'ordery' %>

production:
  <<: *default
  database: ordery
  url: <%= ENV['DATABASE_URL'] %>
