development:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  database: ordery
  pool: 5
  username: 'root'
  password: 'dellF912;'
  socket: /tmp/mysql.sock

test:
  database: ordery

production:
  adapter: mysql2
  pool: 5
  url: '139.59.247.112'
  database: "ordery"
  username: 'playhouse'
  password: 'dellF912;'


